apiVersion: v1
data:
  config.yaml: |
    a: specic ns
kind: ConfigMap
metadata:
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
  name: sentry-test-configmap
  namespace: {{ .Values.global.namespace }}
