apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": "crd-install"
  name: alaudafeaturegates.alauda.io
spec:
  group: alauda.io
  names:
    kind: AlaudaFeatureGate
    listKind: AlaudaFeatureGateList
    plural: alaudafeaturegates
    singular: alaudafeaturegate
    shortNames:
    - afg
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: 'A human readable textual description of the feature gate.'
              type: string
            stage:
              description: 'The lifecycle stage of the feature gate. The value should be one of "Alpha", "Beta", "GA" and "EOF".'
              type: string
            dependency:
              properties:
                featureGates:
                  description: 'A list of feature gates that the feature gate denpends on.'
                  items:
                    type: string
                  type: array
                type:
                  description: 'The type of the denpendency. The value should be "all" or "any". "all" means every denpendency
                    should be enabled to statisfy, "any" means any of the denpendencies is enabled will statisfy.'
                  type: string
              type: object
            enabled:
              description: 'Indicate if the feature gate is enabled or not.'
              type: boolean
          type: object
        status:
          description: 'The status summarizes the current state of the object.'
          properties:
            enabled:
              description: 'Indicate if the feature gate is enabled or not.'
              type: boolean
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true

