apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubevirt.io: ""
    cdi-controller: "read-secret"
  name: kubevirt-cdi-controller-read-secret
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    kubevirt.io: ""
    cdi-controller: "read-secret"
  name: cdi-controller-read-secret-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cdi-sa
  namespace: cdi
roleRef:
  kind: ClusterRole
  name: kubevirt-cdi-controller-read-secret
  apiGroup: rbac.authorization.k8s.io
